[package]
name = "sales-assistant-desktop"
version = "0.1.0"
edition = "2021"

[dependencies]
tauri = { version = "2.0.0", features = ["macos-private-api"] }
tauri-plugin-window-state = "2.0.0"

[build-dependencies]
tauri-build = { version = "2.0.0" }


